// eslint-disable-next-line import/no-anonymous-default-export
export default {
  products: [
    {
      _id: 1,
      name: "suits",
      category: "suits",
      image: "/image/suits.jpeg",
      price: "160",
      countInStock: 10,
      brand: "MEN",
      rating: 4.5,
      numReview: "10",
    },
    {
      _id: 2,
      name: "corporate",
      category: "corporateWear",
      image: "/image/corporate.jpeg",
      countInStock: 10,
      price: "90",
      brand: "KINGS",
      rating: 4,
      numReview: "19",
    },
    {
      _id: 3,
      name: "native",
      category: "nativeWears",
      image: "/image/native.jpeg",
      countInStock: 10,
      price: "60",
      brand: "isioma",
      rating: 5,
      numReview: "19",
    },
    {
      _id: 4,
      name: "native",
      category: "nativeWears",
      imageUrl: "/image/navtive1.jpeg",
      countInStock: 10,
      price: "80",
      brand: "isioma",
      rating: 5,
      numReview: "10",
    },
    {
      _id: 5,
      name: "native",
      category: "nativeWears",
      imageUrl: "/image/native2.jpeg",
      countInStock: 10,
      price: "60",
      brand: "isioma",
      rating: 4,
      numReview: "10",
    },

    {
      _id: "6",
      name: "shirt and jeans",
      category: "shirts",
      imageUrl: "/image/native3.jpeg",
      countInStock: 10,
      price: 60,
      brand: "isioma",
      rating: 4,
      numReview: 10,
      countInShock: 6,
    },
    {
      _id: "7",
      name: "native",
      category: "nativeWears",
      imageUrl: "/image/shirt_and_jeans.jpeg",
      countInStock: 10,
      price: 60,
      brand: "isioma",
      rating: 3,
      numReview: 0,
    },
  ],
};
